name: release
on:
  push:
    tags:
      - v*
jobs:
  release:
    runs-on: ubuntu-latest
    outputs:
      upload_url: ${{ steps.create_release.outputs.upload_url }}
    steps:
      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.DEPLOY_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: osd-tool ${{ github.ref }}
          draft: false
          prerelease: false
  build:
    name: build and upload
    needs: release
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.19

      - name: build linux amd64
        run: go build -o osd-tool_linux_amd64

      - name: build linux arm64
        run: CGO_ENABLED=0 GOOS=linux GOARCH=arm64 go build -o osd-tool_linux_arm64

      - name: build darwin amd64
        run: CGO_ENABLED=0 GOOS=darwin GOARCH=amd64 go build -o osd-tool_darwin_amd64

      - name: build darwin arm64
        run: CGO_ENABLED=0 GOOS=darwin GOARCH=arm64 go build -o osd-tool_darwin_arm64

      #      - name: build windows amd64
      #        run: CGO_ENABLED=0 GOOS=windows GOARCH=amd64 go build -o osd-tool_windows_amd64.exe

      - name: package linux amd64
        run: tar -zcvf osd-tool_linux_amd64.tgz osd-tool_linux_amd64 README.md config.sample.yaml

      - name: package linux arm64
        run: tar -zcvf osd-tool_linux_arm64.tgz osd-tool_linux_arm64 README.md config.sample.yaml

      - name: package darwin amd64
        run: tar -zcvf osd-tool_darwin_amd64.tgz osd-tool_darwin_amd64 README.md config.sample.yaml

      - name: package darwin arm64
        run: tar -zcvf osd-tool_darwin_arm64.tgz osd-tool_darwin_arm64 README.md config.sample.yaml

      #      - name: package windows amd64
      #        run: tar -zcvf osd-tool_windows_amd64.tgz osd-tool_windows_amd64.exe README.md config.sample.yaml

      - name: upload linux amd64
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.DEPLOY_TOKEN }}
        with:
          upload_url: ${{ needs.release.outputs.upload_url }}
          asset_path: osd-tool_linux_amd64.tgz
          asset_name: osd-tool_linux_amd64.tgz
          asset_content_type: application/gzip

      - name: upload linux arm64
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.DEPLOY_TOKEN }}
        with:
          upload_url: ${{ needs.release.outputs.upload_url }}
          asset_path: osd-tool_linux_arm64.tgz
          asset_name: osd-tool_linux_arm64.tgz
          asset_content_type: application/gzip

      - name: upload darwin amd64
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.DEPLOY_TOKEN }}
        with:
          upload_url: ${{ needs.release.outputs.upload_url }}
          asset_path: osd-tool_darwin_amd64.tgz
          asset_name: osd-tool_darwin_amd64.tgz
          asset_content_type: application/gzip

      - name: upload darwin arm64
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.DEPLOY_TOKEN }}
        with:
          upload_url: ${{ needs.release.outputs.upload_url }}
          asset_path: osd-tool_darwin_arm64.tgz
          asset_name: osd-tool_darwin_arm64.tgz
          asset_content_type: application/gzip

#      - name: upload windows amd64
#        uses: actions/upload-release-asset@v1
#        env:
#          GITHUB_TOKEN: ${{ secrets.DEPLOY_TOKEN }}
#        with:
#          upload_url: ${{ needs.release.outputs.upload_url }}
#          asset_path: osd-tool_windows_amd64.tgz
#          asset_name: osd-tool_windows_amd64.tgz
#          asset_content_type: application/gzip